### ISSUE TITLE
Plan query misses fromPlace/toPlace parameters

### ISSUE THREAD

**Issue by jspetrak** [opentripplanner/otp-java-client#16]

**Comment by leonardehrenfried** [comment]
We definitely want this. Would you be interested in contributing?

**Comment by jspetrak** [comment]
@leonardehrenfried I could try although I am not sure how to do conditional parameters (either from or fromPlace) and I am thinking if we want to combine from (GPS) and toPlace or fromPlace and to (GPS), or we want to have both either GPS or locations.

(Currently I use plain Spring Boot GraphQL Client and custom query written to query OTP from my application.)

**Comment by leonardehrenfried** [comment]
Are you trying to set stopIds as from/to? That's the first thing I would try to support and add custom methods to the query builder.

The low-tech approach to writing the actual queries would have to be revisited to make it work.

**Comment by leonardehrenfried** [comment]
I looked at all the Java GraphQL libraries and liked none of them so I came up with my own system. Now we have to make a decision if that is worth keeping.

**Comment by jspetrak** [comment]
I had a brief look into the library implementation and as an immediate improvement, I would create a separate plan query for place-place and require either both be GPS or both be place to select the correct query.

Otherwise we would need to build the parameters in Java and replace not only the value but also the parameter name having the value for GPS not be a simple string but JSON object with lat/lon.

**Comment by leonardehrenfried** [comment]
Please don't create a separate plan query otherwise they will drift apart.

Can you use a simple templating engine like Thymeleaf or Mustache to create a conditional query?

**Comment by leonardehrenfried** [comment]
Actually, scratch that. I think we can replace the from/to with the correctly formatted fromPlace/toPlace.

The interface to the builder can stay the same but you can also supply the raw string or a stop id and the implementation will use the correct format.

If you want to contribute this, I will need tests for this, preferably unit tests.

**Comment by jspetrak** [comment]
I have provided a pull request #18 for this issue. You may review and propose any changes. Thank you.

**Comment by leonardehrenfried** [comment]
Closed by #18
